# Generated by Django 5.2.7 on 2025-10-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_step_delete_recipestep'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='step',
            name='instruction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_steps/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='step',
            name='description',
        ),
    ]
